#!/usr/bin/env tsx
/**
 * Seed 95 synthetic backdated courses to fill the catalogue at 100 total
 * (5 existing sociology seeds + 95 placeholders).
 *
 * Each placeholder carries:
 *   - realistic category/level/tags/status from the coursai-v3 facets
 *   - 10 stub lessons + 5 stub quiz questions (satisfies the schema)
 *   - source:"placeholder" so the cron / /admin can target them for
 *     regeneration once Anthropic billing is restored
 *
 * Dates: 100-day window ending today, skipping the 5 sociology dates
 * (cad-2026-06-14..18). Idempotent — replaceOne upserts by _id.
 *
 * Usage:
 *   pnpm seed:95
 *   pnpm seed:95 --dry
 */

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { CATEGORIES, CourseSchema, LEVELS, STATUSES, type Course, type Lesson, type QuizQuestion } from "../src/lib/schema";
import { upsertCourse } from "../src/lib/mongo";

const DRY = process.argv.includes("--dry") || process.argv.includes("--dry-run");

const SOCIOLOGY_DATES = new Set([
  "2026-06-14", "2026-06-15", "2026-06-16", "2026-06-17", "2026-06-18",
]);

// Per-category sub-areas, tags, thumbnail emoji
const CAT_META: Record<string, { sub: string[]; tags: string[]; emoji: string; topic: string }> = {
  "Foundations":      { sub: ["Prompt Engineering", "Tokens & Context", "Model Selection", "Eval Basics", "Working with the API"], tags: ["Prompts", "LLM", "Basics", "Context", "Eval"], emoji: "🧠", topic: "foundations" },
  "AI Engineering":   { sub: ["Agents", "Tool Use", "RAG Pipelines", "Memory Systems", "Multi-step Reasoning"], tags: ["Agents", "Tools", "RAG", "Memory", "Reasoning"], emoji: "⚙️", topic: "ai-engineering" },
  "Machine Learning": { sub: ["Classical ML", "Regression", "Classification", "Clustering", "Decision Trees"], tags: ["ML", "scikit-learn", "Models", "Training", "Stats"], emoji: "📊", topic: "machine-learning" },
  "Computer Vision":  { sub: ["Image Embeddings", "Object Detection", "OCR", "Segmentation", "Diffusion"], tags: ["CV", "Vision", "Images", "Detection", "Embeddings"], emoji: "👁️", topic: "computer-vision" },
  "NLP":              { sub: ["Tokenization", "Embeddings", "Classification", "NER", "Sentiment"], tags: ["NLP", "Text", "Embeddings", "NER", "Tokens"], emoji: "📝", topic: "nlp" },
  "MLOps":            { sub: ["Model Serving", "Eval Harness", "Cost Tracking", "Caching", "Observability"], tags: ["MLOps", "Deploy", "Eval", "Cost", "Observability"], emoji: "🛠️", topic: "mlops" },
  "AI Product":       { sub: ["Discovery", "Pricing", "UX Patterns", "Trust & Safety", "Roadmaps"], tags: ["Product", "UX", "Pricing", "Discovery", "Safety"], emoji: "🚀", topic: "ai-product" },
  "Generative AI":    { sub: ["Image Gen", "Video Loops", "Audio TTS", "Text-to-Speech", "Multimodal"], tags: ["GenAI", "FLUX", "Video", "Audio", "Multimodal"], emoji: "✨", topic: "generative-ai" },
  "Social Science":   { sub: ["Sociology", "Culture", "Power", "Inequality", "Youth"], tags: ["Sociology", "Society", "Culture", "Inequality", "Youth"], emoji: "🌍", topic: "social-science" },
};

// Deterministic pseudo-random — same seed → same data, makes reruns idempotent
function mulberry32(a: number) {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pad(n: number): string { return String(n).padStart(2, "0"); }
function dateStr(d: Date): string { return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`; }

function backdatedDates(target = 95): string[] {
  const out: string[] = [];
  const today = new Date();
  for (let back = 1; back < 200 && out.length < target; back++) {
    const d = new Date(today);
    d.setUTCDate(d.getUTCDate() - back);
    const s = dateStr(d);
    if (!SOCIOLOGY_DATES.has(s)) out.push(s);
  }
  return out;
}

function buildLessons(category: string, sub: string, rand: () => number): Lesson[] {
  const out: Lesson[] = [];
  for (let r = 1; r <= 10; r++) {
    out.push({
      rank: r,
      title: `${sub} — Lesson ${r}`,
      key_ideas: [
        `${sub} concept #${r}.1 — a foundational idea in ${category.toLowerCase()}.`,
        `${sub} concept #${r}.2 — a common pitfall to avoid.`,
        `${sub} concept #${r}.3 — how to apply this in practice.`,
      ],
      body_md: `## ${sub} — Lesson ${r}\n\nThis is a placeholder lesson generated by \`scripts/seed-95-backdated.ts\`. It satisfies the CAD schema (10–15 lessons, key ideas, body) but the content will be regenerated by the daily cron once Anthropic billing is restored.\n\nIn the meantime, treat the catalogue as a UI demo of the v4.1 shell — the lesson reader, quiz block, and navigation all work; the prose is filler.\n\n**Suggested next read:** Lesson ${r + 1} or the capstone quiz.`,
      duration_min: 1 + Math.floor(rand() * 2),
    });
  }
  return out;
}

function buildQuiz(title: string): QuizQuestion[] {
  return [1, 2, 3, 4, 5].map((rank) => ({
    rank,
    prompt: `Placeholder question ${rank} for "${title}".`,
    choices: ["A foundational concept", "An unrelated product", "A recreational hobby", "A culinary technique"],
    answer_index: 0,
    explanation: "Placeholder quiz. Re-generate via /admin once Anthropic billing is restored.",
  }));
}

function buildCourse(date: string, idx: number): Course {
  const rand = mulberry32(parseInt(date.replace(/-/g, ""), 10));
  const cat = CATEGORIES[idx % CATEGORIES.length];
  const meta = CAT_META[cat];
  const sub = meta.sub[idx % meta.sub.length];
  const variant = Math.floor(idx / meta.sub.length) + 1;
  const title = `${sub} ${String(variant).padStart(2, "0")}`;
  const tagline = `${sub} — a placeholder course in ${cat}. Real content lands once the cron unblocks.`;
  const slug = `cad-${date}`;

  const level: typeof LEVELS[number] = LEVELS[Math.floor(rand() * (idx < 40 ? 1 : idx < 80 ? 2 : 3))] ?? "Beginner";
  // Roll status: ~70% Published, 10% each of Hot / New / Featured
  const r = rand();
  const status: typeof STATUSES[number] =
    r < 0.7 ? "Published" : r < 0.8 ? "Hot" : r < 0.9 ? "New" : "Featured";

  const lessons = buildLessons(cat, sub, rand);
  const total_min = lessons.reduce((s, l) => s + l.duration_min, 0);

  return CourseSchema.parse({
    _id: slug,
    app: "cad",
    kind: "course",
    slug,
    date,
    title,
    tagline,
    topic: meta.topic,
    description: `${title}: a 10-lesson placeholder course in the ${cat} category. The lessons are stubs satisfying the schema; the structure, navigation, and quiz block render exactly as a real course will. Regeneration is queued behind the Anthropic billing unblock.`,
    cover_url: null,
    intro_url: null,
    lessons,
    quiz: buildQuiz(title),
    duration_min: total_min,
    seed: true,
    source: "placeholder",
    created_at: new Date(`${date}T00:00:00Z`).toISOString(),
    meta: { model: "placeholder", prompt_version: 0, run_id: `seed95-${date}` },
    category: cat,
    level,
    tags: meta.tags.slice(0, 3 + Math.floor(rand() * 2)),
    status,
    thumbnail: meta.emoji,
    enrolled: 50 + Math.floor(rand() * 1950),
    rating: Math.round((4.3 + rand() * 0.6) * 10) / 10,
  });
}

async function main() {
  const dates = backdatedDates(95);
  console.log(`[seed:95] generating ${dates.length} courses (${dates[dates.length - 1]} → ${dates[0]})`);

  const courses = dates.map((d, i) => buildCourse(d, i));

  // category coverage summary
  const byCat: Record<string, number> = {};
  for (const c of courses) byCat[c.category ?? "?"] = (byCat[c.category ?? "?"] ?? 0) + 1;
  console.log(`[seed:95] per-category:`);
  for (const [k, v] of Object.entries(byCat).sort()) {
    console.log(`  ${k.padEnd(18)} ${v}`);
  }

  if (DRY) {
    console.log(`[seed:95] --dry — first course sample:`);
    console.log(JSON.stringify({ ...courses[0], lessons: `[${courses[0].lessons.length} lessons]`, quiz: `[${courses[0].quiz.length} quiz]` }, null, 2));
    return;
  }

  let ok = 0;
  for (const c of courses) {
    await upsertCourse(c);
    ok++;
    if (ok % 10 === 0) console.log(`  · ${ok}/${courses.length} upserted`);
  }
  console.log(`[seed:95] done — ${ok}/${courses.length} courses in FLEET.lists`);
}

main().catch((e) => {
  console.error("[seed:95] FATAL:", e);
  process.exit(1);
});
